---
- name: Jenkins Ansible Deployment
  hosts: all
  become: true

  tasks:
    - name: run docker container
      docker_container:
        name: web
        image: nginx
        tty: true
        state: started
        ports:
          - "80:80"
